service: simple-aws-lambda

provider:
  name: aws
  runtime: java11
  profile: serverless-admin
  region: us-east-2
  timeout: 10
  memorySize: 1024

package:
  artifact: target/simple-aws-lambda.jar

functions:
  simpleLambda:
    handler: lambda.SimpleLambda
