service: simple-aws-lambda

provider:
  name: aws
  runtime: java11
  profile: serverless-admin
  region: eu-central-1
  timeout: 10
  memorySize: 1024
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource:
        - 'arn:aws:s3:::${self:custom.myBucket}/*'
        - !Join ['', ['arn:aws:s3:::', !Ref ServerlessDeploymentBucket, '/*']]

custom:
  myBucket: rieckpil-custom-bucket

package:
  artifact: target/simple-aws-lambda.jar

functions:
  simpleLambda:
    handler: de.rieckpil.blog.SimpleLambda
    environment:
      MESSAGE: Duke42
  simpleHttp:
    handler: de.rieckpil.blog.SimpleHttpHandler
    events:
      - http:
          method: POST
          path: /simple
  simpleEventTrigger:
    handler: de.rieckpil.blog.SimpleEventHandler
    events:
      - s3:
          bucket: ${self:custom.myBucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .png
  simpleScheduledTrigger:
    handler: de.rieckpil.blog.SimpleScheduledHandler
    events:
      - schedule: rate(1 minute)
  fullControlLambda:
    handler: de.rieckpil.blog.FullControlLambda
